[build]
  command = "npm run generate"
  publish = "dist"

[[redirects]]
  from = "/pasta1/*"
  to = "/pasta2/:splat"
  status = 200

[[redirects]]
  from = "/rota-antiga"
  to = "/nova-rota"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"